name: Node.js Package
on:
  workflow_dispatch:
    inputs:
      doc:
        description: 'Run documentation'     
        required: true
        default: 'warning'
      tags:
        description: 'Documentation update' 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm install
    # Build
    - run: npm run deploy
